/**
 * tf2_stocks.go
 * 
 * Copyright 2020 Nirari Technologies, Alliedmodders LLC.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 */

package main

import (
	"tf2"
)

type (
	TFResourceType int
)

const (
	TF_CONDFLAG_NONE =             0
	TF_CONDFLAG_SLOWED =          (1 << 0)
	TF_CONDFLAG_ZOOMED =          (1 << 1)
	TF_CONDFLAG_DISGUISING =      (1 << 2)
	TF_CONDFLAG_DISGUISED =       (1 << 3)
	TF_CONDFLAG_CLOAKED =         (1 << 4)
	TF_CONDFLAG_UBERCHARGED =     (1 << 5)
	TF_CONDFLAG_TELEPORTGLOW =    (1 << 6)
	TF_CONDFLAG_TAUNTING =        (1 << 7)
	TF_CONDFLAG_UBERCHARGEFADE =  (1 << 8)
	TF_CONDFLAG_CLOAKFLICKER =    (1 << 9)
	TF_CONDFLAG_TELEPORTING =     (1 << 10)
	TF_CONDFLAG_KRITZKRIEGED =    (1 << 11)
	TF_CONDFLAG_DEADRINGERED =    (1 << 13)
	TF_CONDFLAG_BONKED =          (1 << 14)
	TF_CONDFLAG_DAZED =           (1 << 15)
	TF_CONDFLAG_BUFFED =          (1 << 16)
	TF_CONDFLAG_CHARGING =        (1 << 17)
	TF_CONDFLAG_DEMOBUFF =        (1 << 18)
	TF_CONDFLAG_CRITCOLA =        (1 << 19)
	TF_CONDFLAG_INHEALRADIUS =    (1 << 20)
	TF_CONDFLAG_HEALING =         (1 << 21)
	TF_CONDFLAG_ONFIRE =          (1 << 22)
	TF_CONDFLAG_OVERHEALED =      (1 << 23)
	TF_CONDFLAG_JARATED =         (1 << 24)
	TF_CONDFLAG_BLEEDING =        (1 << 25)
	TF_CONDFLAG_DEFENSEBUFFED =   (1 << 26)
	TF_CONDFLAG_MILKED =          (1 << 27)
	TF_CONDFLAG_MEGAHEAL =        (1 << 28)
	TF_CONDFLAG_REGENBUFFED =     (1 << 29)
	TF_CONDFLAG_MARKEDFORDEATH =  (1 << 30)
	
	TF_DEATHFLAG_KILLERDOMINATION =   (1 << 0)
	TF_DEATHFLAG_ASSISTERDOMINATION = (1 << 1)
	TF_DEATHFLAG_KILLERREVENGE =      (1 << 2)
	TF_DEATHFLAG_ASSISTERREVENGE =    (1 << 3)
	TF_DEATHFLAG_FIRSTBLOOD =         (1 << 4)
	TF_DEATHFLAG_DEADRINGER =         (1 << 5)
	TF_DEATHFLAG_INTERRUPTED =        (1 << 6)
	TF_DEATHFLAG_GIBBED =             (1 << 7)
	TF_DEATHFLAG_PURGATORY =          (1 << 8)
	TF_DEATHFLAG_MINIBOSS =           (1 << 9)
	TF_DEATHFLAG_AUSTRALIUM =         (1 << 10)
	
	TF_CUSTOM_HEADSHOT = 1
	TF_CUSTOM_BACKSTAB
	TF_CUSTOM_BURNING
	TF_CUSTOM_WRENCH_FIX
	TF_CUSTOM_MINIGUN
	TF_CUSTOM_SUICIDE
	TF_CUSTOM_TAUNT_HADOUKEN
	TF_CUSTOM_BURNING_FLARE
	TF_CUSTOM_TAUNT_HIGH_NOON
	TF_CUSTOM_TAUNT_GRAND_SLAM
	TF_CUSTOM_PENETRATE_MY_TEAM
	TF_CUSTOM_PENETRATE_ALL_PLAYERS
	TF_CUSTOM_TAUNT_FENCING
	TF_CUSTOM_PENETRATE_HEADSHOT
	TF_CUSTOM_TAUNT_ARROW_STAB
	TF_CUSTOM_TELEFRAG
	TF_CUSTOM_BURNING_ARROW
	TF_CUSTOM_FLYINGBURN
	TF_CUSTOM_PUMPKIN_BOMB
	TF_CUSTOM_DECAPITATION
	TF_CUSTOM_TAUNT_GRENADE
	TF_CUSTOM_BASEBALL
	TF_CUSTOM_CHARGE_IMPACT
	TF_CUSTOM_TAUNT_BARBARIAN_SWING
	TF_CUSTOM_AIR_STICKY_BURST
	TF_CUSTOM_DEFENSIVE_STICKY
	TF_CUSTOM_PICKAXE
	TF_CUSTOM_ROCKET_DIRECTHIT
	TF_CUSTOM_TAUNT_UBERSLICE
	TF_CUSTOM_PLAYER_SENTRY
	TF_CUSTOM_STANDARD_STICKY
	TF_CUSTOM_SHOTGUN_REVENGE_CRIT
	TF_CUSTOM_TAUNT_ENGINEER_SMASH
	TF_CUSTOM_BLEEDING
	TF_CUSTOM_GOLD_WRENCH
	TF_CUSTOM_CARRIED_BUILDING
	TF_CUSTOM_COMBO_PUNCH
	TF_CUSTOM_TAUNT_ENGINEER_ARM
	TF_CUSTOM_FISH_KILL
	TF_CUSTOM_TRIGGER_HURT
	TF_CUSTOM_DECAPITATION_BOSS
	TF_CUSTOM_STICKBOMB_EXPLOSION
	TF_CUSTOM_AEGIS_ROUND
	TF_CUSTOM_FLARE_EXPLOSION
	TF_CUSTOM_BOOTS_STOMP
	TF_CUSTOM_PLASMA
	TF_CUSTOM_PLASMA_CHARGED
	TF_CUSTOM_PLASMA_GIB
	TF_CUSTOM_PRACTICE_STICKY
	TF_CUSTOM_EYEBALL_ROCKET
	TF_CUSTOM_HEADSHOT_DECAPITATION
	TF_CUSTOM_TAUNT_ARMAGEDDON
	TF_CUSTOM_FLARE_PELLET
	TF_CUSTOM_CLEAVER
	TF_CUSTOM_CLEAVER_CRIT
	TF_CUSTOM_SAPPER_RECORDER_DEATH
	TF_CUSTOM_MERASMUS_PLAYER_BOMB
	TF_CUSTOM_MERASMUS_GRENADE
	TF_CUSTOM_MERASMUS_ZAP
	TF_CUSTOM_MERASMUS_DECAPITATION
	TF_CUSTOM_CANNONBALL_PUSH
	TF_CUSTOM_TAUNT_ALLCLASS_GUITAR_RIFF
	TF_CUSTOM_THROWABLE
	TF_CUSTOM_THROWABLE_KILL
	TF_CUSTOM_SPELL_TELEPORT
	TF_CUSTOM_SPELL_SKELETON
	TF_CUSTOM_SPELL_MIRV
	TF_CUSTOM_SPELL_METEOR
	TF_CUSTOM_SPELL_LIGHTNING
	TF_CUSTOM_SPELL_FIREBALL
	TF_CUSTOM_SPELL_MONOCULUS
	TF_CUSTOM_SPELL_BLASTJUMP
	TF_CUSTOM_SPELL_BATS
	TF_CUSTOM_SPELL_TINY
	TF_CUSTOM_KART
	TF_CUSTOM_GIANT_HAMMER
	TF_CUSTOM_RUNE_REFLECT
	TF_CUSTOM_DRAGONS_FURY_IGNITE
	TF_CUSTOM_DRAGONS_FURY_BONUS_BURNING
	TF_CUSTOM_SLAP_KILL
	TF_CUSTOM_CROC
	TF_CUSTOM_TAUNTATK_GASBLAST
	TF_CUSTOM_AXTINGUISHER_BOOSTED
	
	TF_WEAPON_NONE = 0
	TF_WEAPON_BAT
	TF_WEAPON_BAT_WOOD
	TF_WEAPON_BOTTLE
	TF_WEAPON_FIREAXE
	TF_WEAPON_CLUB
	TF_WEAPON_CROWBAR
	TF_WEAPON_KNIFE
	TF_WEAPON_FISTS
	TF_WEAPON_SHOVEL
	TF_WEAPON_WRENCH
	TF_WEAPON_BONESAW
	TF_WEAPON_SHOTGUN_PRIMARY
	TF_WEAPON_SHOTGUN_SOLDIER
	TF_WEAPON_SHOTGUN_HWG
	TF_WEAPON_SHOTGUN_PYRO
	TF_WEAPON_SCATTERGUN
	TF_WEAPON_SNIPERRIFLE
	TF_WEAPON_MINIGUN
	TF_WEAPON_SMG
	TF_WEAPON_SYRINGEGUN_MEDIC
	TF_WEAPON_TRANQ
	TF_WEAPON_ROCKETLAUNCHER
	TF_WEAPON_GRENADELAUNCHER
	TF_WEAPON_PIPEBOMBLAUNCHER
	TF_WEAPON_FLAMETHROWER
	TF_WEAPON_GRENADE_NORMAL
	TF_WEAPON_GRENADE_CONCUSSION
	TF_WEAPON_GRENADE_NAIL
	TF_WEAPON_GRENADE_MIRV
	TF_WEAPON_GRENADE_MIRV_DEMOMAN
	TF_WEAPON_GRENADE_NAPALM
	TF_WEAPON_GRENADE_GAS
	TF_WEAPON_GRENADE_EMP
	TF_WEAPON_GRENADE_CALTROP
	TF_WEAPON_GRENADE_PIPEBOMB
	TF_WEAPON_GRENADE_SMOKE_BOMB
	TF_WEAPON_GRENADE_HEAL
	TF_WEAPON_GRENADE_STUNBALL
	TF_WEAPON_GRENADE_JAR
	TF_WEAPON_GRENADE_JAR_MILK
	TF_WEAPON_PISTOL
	TF_WEAPON_PISTOL_SCOUT
	TF_WEAPON_REVOLVER
	TF_WEAPON_NAILGUN
	TF_WEAPON_PDA
	TF_WEAPON_PDA_ENGINEER_BUILD
	TF_WEAPON_PDA_ENGINEER_DESTROY
	TF_WEAPON_PDA_SPY
	TF_WEAPON_BUILDER
	TF_WEAPON_MEDIGUN
	TF_WEAPON_GRENADE_MIRVBOMB
	TF_WEAPON_FLAMETHROWER_ROCKET
	TF_WEAPON_GRENADE_DEMOMAN
	TF_WEAPON_SENTRY_BULLET
	TF_WEAPON_SENTRY_ROCKET
	TF_WEAPON_DISPENSER
	TF_WEAPON_INVIS
	TF_WEAPON_FLAREGUN
	TF_WEAPON_LUNCHBOX
	TF_WEAPON_JAR
	TF_WEAPON_COMPOUND_BOW
	TF_WEAPON_BUFF_ITEM
	TF_WEAPON_PUMPKIN_BOMB
	TF_WEAPON_SWORD
	TF_WEAPON_DIRECTHIT
	TF_WEAPON_LIFELINE
	TF_WEAPON_LASER_POINTER
	TF_WEAPON_DISPENSER_GUN
	TF_WEAPON_SENTRY_REVENGE
	TF_WEAPON_JAR_MILK
	TF_WEAPON_HANDGUN_SCOUT_PRIMARY
	TF_WEAPON_BAT_FISH
	TF_WEAPON_CROSSBOW
	TF_WEAPON_STICKBOMB
	TF_WEAPON_HANDGUN_SCOUT_SEC
	TF_WEAPON_SODA_POPPER
	TF_WEAPON_SNIPERRIFLE_DECAP
	TF_WEAPON_RAYGUN
	TF_WEAPON_PARTICLE_CANNON
	TF_WEAPON_MECHANICAL_ARM
	TF_WEAPON_DRG_POMSON
	TF_WEAPON_BAT_GIFTWRAP
	TF_WEAPON_GRENADE_ORNAMENT
	TF_WEAPON_RAYGUN_REVENGE
	TF_WEAPON_PEP_BRAWLER_BLASTER
	TF_WEAPON_CLEAVER
	TF_WEAPON_GRENADE_CLEAVER
	TF_WEAPON_STICKY_BALL_LAUNCHER
	TF_WEAPON_GRENADE_STICKY_BALL
	TF_WEAPON_SHOTGUN_BUILDING_RESCUE
	TF_WEAPON_CANNON
	TF_WEAPON_THROWABLE
	TF_WEAPON_GRENADE_THROWABLE
	TF_WEAPON_PDA_SPY_BUILD
	TF_WEAPON_GRENADE_WATERBALLOON
	TF_WEAPON_HARVESTER_SAW
	TF_WEAPON_SPELLBOOK
	TF_WEAPON_SPELLBOOK_PROJECTILE
	TF_WEAPON_SNIPERRIFLE_CLASSIC
	TF_WEAPON_PARACHUTE
	TF_WEAPON_GRAPPLINGHOOK
	TF_WEAPON_PASSTIME_GUN
	TF_WEAPON_CHARGED_SMG
	TF_WEAPON_BREAKABLE_SIGN
	TF_WEAPON_ROCKETPACK
	TF_WEAPON_SLAP
	TF_WEAPON_JAR_GAS
	TF_WEAPON_GRENADE_JAR_GAS
	TF_WEAPON_FLAME_BALL
	
	TFWeaponSlot_Primary
	TFWeaponSlot_Secondary
	TFWeaponSlot_Melee
	TFWeaponSlot_Grenade
	TFWeaponSlot_Building
	TFWeaponSlot_PDA
	TFWeaponSlot_Item1
	TFWeaponSlot_Item2
	
	TF_FLAGEVENT_PICKEDUP = 1
	TF_FLAGEVENT_CAPTURED
	TF_FLAGEVENT_DEFENDED
	TF_FLAGEVENT_DROPPED
	TF_FLAGEVENT_RETURNED
	
	TFResource_Ping = TFResourceType(0)
	TFResource_Score
	TFResource_Deaths
	TFResource_TotalScore
	TFResource_Captures
	TFResource_Defenses
	TFResource_Dominations
	TFResource_Revenge
	TFResource_BuildingsDestroyed
	TFResource_Headshots
	TFResource_Backstabs
	TFResource_HealPoints
	TFResource_Invulns
	TFResource_Teleports
	TFResource_ResupplyPoints
	TFResource_KillAssists
	TFResource_MaxHealth
	TFResource_PlayerClass
	
	TFResourceNames = [...]string{
		"m_iPing",
		"m_iScore",
		"m_iDeaths",
		"m_iTotalScore",
		"m_iCaptures",
		"m_iDefenses",
		"m_iDominations",
		"m_iRevenge",
		"m_iBuildingsDestroyed",
		"m_iHeadshots",
		"m_iBackstabs",
		"m_iHealPoints",
		"m_iInvulns",
		"m_iTeleports",
		"m_iResupplyPoints",
		"m_iKillAssists",
		"m_iMaxHealth",
		"m_iPlayerClass",
	}
)

func TF2_RemoveWearable(client, wearable Entity)
func TF2_GetClientTeam(client int) TFTeam
func TF2_ChangeClientTeam(client int, team TFTeam)
func TF2_GetPlayerClass(client int) TFClassType
func TF2_SetPlayerClass(client int, classType TFClassType, weapons, persistent bool)
func TF2_RemoveWeaponSlot(client, slot int)
func TF2_RemoveAllWeapons(client int)
func TF2_IsPlayerInCondition(client int, cond TFCond) bool
func TF2_GetObjectType(entity Entity) TFObjectType
func TF2_GetObjectMode(entity Entity) TFObjectMode
