/**
 * gopawn.go
 * 
 * Copyright 2020 Nirari Technologies.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 */

package ASTtoSP


import (
	"fmt"
	"strings"
	//"go/token"
	//"go/scanner"
	//"go/parser"
	"go/ast"
	//"go/types"   /// Golang's Type system.
)


type SPGen struct {
	GenCode         strings.Builder
	SrcGoAST        *ast.File
	GenInclude      bool
}

func (spg *SPGen) AnalyzeImports() {
	for _, include := range spg.SrcGoAST.Imports {
		spg.GenCode.WriteString("#include <" + include.Path.Value[1 : len(include.Path.Value)-1] + ">\n")
	}
}

func (spg *SPGen) AnalyzeFile() {
	spg.GenCode.WriteString("/// file generated by the GoToSourcePawn Transpiler v0.2a\n/// Copyright 2020 (C) Kevin Yonan aka Nergal, Assyrianic.\n/// GoToSourcePawn Project is licensed under MIT.\n/// link: 'https://github.com/assyrianic/Go2SourcePawn'\n\n")
	
	spg.AnalyzeImports()
}

func (spg *SPGen) PrintAST() {
	ast.Inspect(spg.SrcGoAST, func(n ast.Node) bool {
		if n != nil {
			fmt.Printf("%T: ", n)
			fmt.Println(n)
		}
		return true
	})
}